/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CodeRouteImport } from './routes/code'
import { Route as BobRouteImport } from './routes/bob'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BobThreadIdRouteImport } from './routes/bob.$threadId'
import { Route as ApiBobRouteImport } from './routes/api/bob'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const BobRoute = BobRouteImport.update({
  id: '/bob',
  path: '/bob',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BobThreadIdRoute = BobThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => BobRoute,
} as any)
const ApiBobRoute = ApiBobRouteImport.update({
  id: '/api/bob',
  path: '/api/bob',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bob': typeof BobRouteWithChildren
  '/code': typeof CodeRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/keys': typeof KeysRoute
  '/playground': typeof PlaygroundRoute
  '/settings': typeof SettingsRoute
  '/api/bob': typeof ApiBobRoute
  '/bob/$threadId': typeof BobThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bob': typeof BobRouteWithChildren
  '/code': typeof CodeRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/keys': typeof KeysRoute
  '/playground': typeof PlaygroundRoute
  '/settings': typeof SettingsRoute
  '/api/bob': typeof ApiBobRoute
  '/bob/$threadId': typeof BobThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bob': typeof BobRouteWithChildren
  '/code': typeof CodeRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/keys': typeof KeysRoute
  '/playground': typeof PlaygroundRoute
  '/settings': typeof SettingsRoute
  '/api/bob': typeof ApiBobRoute
  '/bob/$threadId': typeof BobThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bob'
    | '/code'
    | '/dashboard'
    | '/docs'
    | '/faq'
    | '/keys'
    | '/playground'
    | '/settings'
    | '/api/bob'
    | '/bob/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bob'
    | '/code'
    | '/dashboard'
    | '/docs'
    | '/faq'
    | '/keys'
    | '/playground'
    | '/settings'
    | '/api/bob'
    | '/bob/$threadId'
  id:
    | '__root__'
    | '/'
    | '/bob'
    | '/code'
    | '/dashboard'
    | '/docs'
    | '/faq'
    | '/keys'
    | '/playground'
    | '/settings'
    | '/api/bob'
    | '/bob/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BobRoute: typeof BobRouteWithChildren
  CodeRoute: typeof CodeRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  FaqRoute: typeof FaqRoute
  KeysRoute: typeof KeysRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SettingsRoute: typeof SettingsRoute
  ApiBobRoute: typeof ApiBobRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bob': {
      id: '/bob'
      path: '/bob'
      fullPath: '/bob'
      preLoaderRoute: typeof BobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bob/$threadId': {
      id: '/bob/$threadId'
      path: '/$threadId'
      fullPath: '/bob/$threadId'
      preLoaderRoute: typeof BobThreadIdRouteImport
      parentRoute: typeof BobRoute
    }
    '/api/bob': {
      id: '/api/bob'
      path: '/api/bob'
      fullPath: '/api/bob'
      preLoaderRoute: typeof ApiBobRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BobRouteChildren {
  BobThreadIdRoute: typeof BobThreadIdRoute
}

const BobRouteChildren: BobRouteChildren = {
  BobThreadIdRoute: BobThreadIdRoute,
}

const BobRouteWithChildren = BobRoute._addFileChildren(BobRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BobRoute: BobRouteWithChildren,
  CodeRoute: CodeRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  FaqRoute: FaqRoute,
  KeysRoute: KeysRoute,
  PlaygroundRoute: PlaygroundRoute,
  SettingsRoute: SettingsRoute,
  ApiBobRoute: ApiBobRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
